
---
- name: Configure Docker
  hosts: jenkins-server 
  become: true
  tasks:
    - name: Add ec2-user to Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted
      become: true

    - name: Verify Docker group membership
      shell: "groups ec2-user"
      register: user_groups
      changed_when: false

    - name: Display Docker group membership
      debug:
        msg: "{{ user_groups.stdout }}"

    - name: Check Docker version
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Display Docker version
      debug:
        msg: "{{ docker_version.stdout }}"

