apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    owner: ahmed
    company: ivolve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        owner: ahmed
        company: ivolve
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
