---
- name: Send email using Ansible
  hosts: localhost
  tasks:
    - name: Send email
      mail:
        host: smtp.gmail.com
        port: 587
        username: your-email@gmail.com
        password: your-app-password
        to: recipient@gmail.com
        subject: Test Email Subject
        body: This is a test email sent from Ansible.
        secure: starttls

